version: '3.4'

services:
  cadeoerro:
    container_name: cadeoerro
    image: cadeoerro
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile